# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lpbdcpp <- function(alpha_d, Sigma_Inv, kappa_t, kappa_s, mu_d, docs, V, mv) {
    .Call(`_sts_lpbdcpp`, alpha_d, Sigma_Inv, kappa_t, kappa_s, mu_d, docs, V, mv)
}

lgaecpp <- function(alpha_d, Sigma_Inv, kappa_t, kappa_s, mu_d, docs, V, mv) {
    .Call(`_sts_lgaecpp`, alpha_d, Sigma_Inv, kappa_t, kappa_s, mu_d, docs, V, mv)
}

esthcpp <- function(alpha_d, kappa_t, kappa_s, Sigma_Inv, doc, V, mv) {
    .Call(`_sts_esthcpp`, alpha_d, kappa_t, kappa_s, Sigma_Inv, doc, V, mv)
}

